### ISSUE TITLE
When I try to add a dependency to my project, I get this error.

### ISSUE THREAD

**Issue by vfxbro** [AdarshaBista/FlutterDeepSpeech#1]
[flutter_deep_speech] flutter pub get
Running "flutter pub get" in flutter_deep_speech...
Resolving dependencies...
Error on line 39, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷
39 │   flutter_deep_speech:
   │   ^^^^^^^^^^^^^^^^^^^
   ╵
pub get failed
command: "/Users/bro/development/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/bro/development/flutter",
  "PUB_ENVIRONMENT": "vscode.dart-code:flutter_cli:get",
  "PUB_CACHE": "/Users/bro/.pub-cache",
}
exit code: 65

exit code 65

**Comment by AdarshaBista** [comment]
Looks like the name of your app is also `flutter_deep_speech` which is the same name as this package. Can you try changing the name of your app and try to add this package as a dependency?

**Comment by vfxbro** [comment]
Thx!
But on the latest versions of Flutter does not run.

`Launching lib\main.dart on Android SDK built for x86 in debug mode...
main.dart:1

FAILURE: Build failed with an exception.

`
Launching lib\main.dart on Android SDK built for x86 in debug mode...
main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compressDebugAssets'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CompressAssetsWorkAction
   > Java heap space
`
   
   [√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [Version 10.0.19044.2728], locale ru-RU)
    • Flutter version 3.7.7 on channel stable at D:\Program Files\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2ad6cd72c0 (9 days ago), 2023-03-08 09:41:59 -0800
    • Engine revision 1837b5be5f
    • Dart version 2.19.4
    • DevTools version 2.20.1
    
    [√] Android Studio (version 2022.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-9505619)

[√] VS Code (version 1.76.2)
    • VS Code at C:\Users\vfxbro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.60.0

**Comment by AdarshaBista** [comment]
I cannot say exactly what's causing the issue without more details. Can you try some of the solutions provided in the following links and see it that helps:

https://stackoverflow.com/questions/65578695/execution-failed-for-task-appcompressdebugassets
https://github.com/flutter/flutter/issues/80719

If the issue still exists, please post the output of `flutter run -v`.

**Comment by AbdouEsi** [comment]
[  +11 ms] "flutter run" took 3,688ms.
[  +22 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:499:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1381:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous s

**Comment by AdarshaBista** [comment]
Please try version `0.0.3` of the package and see if it fixes the issue.

Closing this for now, feel free to reopen if the issue persists.
