### ISSUE TITLE
Adding ios support

### ISSUE THREAD

**Issue by sonnyvesali** [AdarshaBista/FlutterDeepSpeech#4]
Hi I would love to contribute & get iOS support, I've seen a [few articles](https://techblog.geekyants.com/mozilla-deepspeech-engine-in-flutter-using-dart-ffi) that show how to do this but I'm not sure if they're outdated, would love to collaborate on this b/c I have a use case for running a local speech to text model in my ios/android flutter app.

Cheers!

**Comment by AdarshaBista** [comment]
Sure, please feel free to create a PR.
